# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Technologies
email: xdyang@zjgsu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  This website provides tons of information about the web technology courses and
   the related information. Please come here often and enjoy surfing in the ocean of 
   the fantastic web technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.webcourseinfo.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: pygments
#gems: 
#- jekyll-mentions
#- jemoji
#- jekyll-redirect-from
#- jekyll-sitemap

#- jekyll-feed